name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - develop
      - release/v1.3.0
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
      - develop
      - release/v1.3.0
 
jobs:
  test:
    runs-on: ubuntu-latest  # Of windows-latest/macOS-latest als specifiek platform nodig is
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-android
 
      - name: Herstel afhankelijkheden
        run: dotnet restore
 
      - name: Bouw de applicatie
        run: dotnet build --configuration Release --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
